src/Entity/Promotions.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use App\Repository\PromotionsRepository;

#[ORM\Entity(repositoryClass: PromotionsRepository::class)]
class Promotions
{
    use CreatedAtTrait;
    use SlugTrait;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Products::class, inversedBy: 'promotions')]
    #[ORM\JoinColumn(nullable: false)]
    private $product;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(type: 'integer')]
    private $discount;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Products
    {
        return $this->product;
    }

    public function setProduct(?Products $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }
}

src/Controller/Admin/CategoriesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Categories;
use App\Form\CategoriesFormType;
use App\Repository\CategoriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/admin/categories', name: 'admin_categories_')]
class CategoriesController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(CategoriesRepository $categoriesRepository): Response
    {
        $categories = $categoriesRepository->findBy([], ['categoryOrder' => 'asc']);

        return $this->render('admin/categories/index.html.twig', compact('categories'));
    }

    #[Route('/ajout', name: 'add')]
    public function add(Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        //On crée un "nouveau produit"
        $categorie = new Categories();

        // On crée le formulaire
        $categorieForm = $this->createForm(CategoriesFormType::class, $categorie);

        // On traite la requête du formulaire
        $categorieForm->handleRequest($request);

        //On vérifie si le formulaire est soumis ET valide
        if($categorieForm->isSubmitted() && $categorieForm->isValid()){

            // On génère le slug
            $slug = $slugger->slug($categorie->getName());
            $categorie->setSlug($slug);

            // On stocke
            $em->persist($categorie);
            $em->flush();

            $this->addFlash('success', 'Catégorie ajouté avec succès');

            // On redirige
            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('admin/categories/add.html.twig',[
            'categorieForm' => $categorieForm->createView()
        ]);
    }

    #[Route('/suppression/{id}', name: 'delete')]
    public function delete(Categories $categorie, EntityManagerInterface $em): Response
    {
        // On vérifie si l'utilisateur peut supprimer avec le Voter
        $this->denyAccessUnlessGranted('ROLE_ADMIN', $categorie);

        // Supprimer le produit de la base de données
        $em->remove($categorie);
        $em->flush();

        $this->addFlash('success', 'Catégorie supprimé avec succès');

        // Rediriger vers la liste des produits ou une autre page appropriée
        return $this->redirectToRoute('admin_categories_index');
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\Products;
use App\Entity\Promotions;
use App\Repository\ProductsRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/categories', name: 'categories_')]
class CategoriesController extends AbstractController
{
    #[Route('/{slug}', name: 'list')]
    public function list(Categories $category, ProductsRepository $productsRepository,ManagerRegistry $managerRegistry, Request $request): Response
    {
        //On va chercher le numéro de page dans l'url
        $page = $request->query->getInt('page', 1);

        //On va chercher la liste des produits de la catégorie et les promotions
        $entityManager = $managerRegistry->getManager();
        $productsData = $productsRepository->findProductsPaginated($page, $category->getSlug(), 4);
        $products = $entityManager->getRepository(Products::class)->findAll();
        $promotions = $entityManager->getRepository(Promotions::class)->findAll();

        return $this->render('categories/list.html.twig', compact('category', 'productsData', 'products', 'promotions'));
    }
}

templates/categories/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits de la catégorie {{ category.name }}{% endblock %}

{% block body %}
    <main class="container">
        <section class="row">
            <div class="col-12">
                <h1>Nos {{ category.name|lower }}</h1>
            </div>
            <div class="row justify-content-center">
            {% for product in productsData.data %}
                {% set discount = null %}
                {% for promotion in promotions %}
                    {% if promotion.startDate|date('Y-m-d') <= 'now'|date('Y-m-d') and promotion.endDate|date('Y-m-d') >= 'now'|date('Y-m-d') and promotion.product.id == product.id %}
                        {% set discount = promotion %}
                    {% endif %}
                {% endfor %}
                
                <div class="col-3 mb-3">
                    <article class="card {% if discount is not empty %}promo{% endif %} h-100">
                        {% if product.images is not empty %}
                            <img src="{{ asset('assets/uploads/products/mini/300x300-' ~ product.images[0].name ) }}" class="card-img-top" alt="{{ product.name }}">
                        {% endif %}
                        <div class="card-body">
                            {% if discount is not empty %}
                                <p class="card-field card-price">Prix : <s>{{ product.price / 100 }}</s> &#x2794; <span>{{ product.price / 100 - (product.price / 100 * discount.discount / 100) }}€ (-{{ discount.discount }}%)</span></p>
                            {% else %}
                                <p class="card-field card-price">Prix : {{ product.price / 100 }}€</p>
                            {% endif %}
                            <h4 class="card-field card-title">{{ product.name }}</h4>
                            <p class="card-field card-text">{{ product.description }}</p>
                        </div>
                    </article>
                </div>
            {% endfor %}
            </div>
        </section>
    </main>
{% endblock %}